Update guestOpsManagement.pl
Adding support for vSphere 6.0 and suggesting change to error message in order to limit confusion.

Error used to say the following, which would imply that 6.0 was supported:
Error: This script only supports vSphere "5.0.0 5.1.0 5.5.0" or greater!